### ISSUE TITLE
US-18: Create a task list for students

### ISSUE THREAD

**Issue by CybRam** [charlotteglen/WIZARD7-SOEN341_Project_F24#26]
### Narrative:

As a Teacher,
I want to be able to create a list of tasks that my students can view
so that they understand what they need to do.

### Acceptance Criteria:

1. The instructor can create a task list.
2. The created tasks are saved and displayed accurately on the students' dashboard.
3. The feature does not create errors or conflicts with other components.

### Priority:

HIGH

### Estimation:

8 story points

### Definition of Done:

- [ ]  Code is written, reviewed, and merged into the main branch.
- [ ]  All acceptance criteria are met and tested.
- [ ]  The feature is viewed and validated by the TA during demo.
